### ISSUE TITLE
Filter Layer Color in FontView.py Error

### ISSUE THREAD

**Issue by weiweihuanghuang** [HugoJourdan/Glyphs-Script#3]
Tried to run it in the font view:

```
Traceback (most recent call last):
  File "Filter Layer Color in FontView.py", line 45
    Glyphs.font.customParameters["glyphOrder"] = GenerateLayerColorGlyphOrder()
  File "Filter Layer Color in FontView.py", line 20, in GenerateLayerColorGlyphOrder
    colorMeaning = Map_Keys(Get_Key_File())
NameError: name 'Map_Keys' is not defined
```

**Comment by HugoJourdan** [comment]
I think I fixed it, can you try again ?
